#! /bin/sh

### BEGIN INIT INFO
# Provides:		mitiab
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Ipseity web control panel
### END INIT INFO

set -e

# Gleefully pilfered from:
# http://stackoverflow.com/questions/5500943/best-init-script-for-running-an-application-as-a-separate-user

SITENAME="mitiab"
PIDFILE=/var/run/site-$SITENAME.pid
SCRIPT=bin/app.pl
USER=root
ACTIVATE=/home/www/project/env/bin/activate
BIND=127.0.0.1:80

export PYTHONPATH="/usr/share"
export TZ="GB"

case "$1" in
  start)
        source $ACTIVATE
        gunicorn --daemon --bind=$BIND --pid=$PIDFILE --workers=4 --log-file=/var/log/$SITENAME.log $SITENAME:app

    if [ $? = 0 ]; then echo "Started $SITENAME."; fi
    ;;
  stop)
    /usr/local/bin/uwsgi --stop $PIDFILE
    if [ $? = 0 ]; then echo "Stopped $SITENAME."; fi
    ;;
  restart)
    /usr/local/bin/uwsgi --reload $PIDFILE
    if [ $? = 0 ]; then echo "Restarted $SITENAME."; fi
    ;;
  status)
    if [ -f $PIDFILE ]; then
      #pgrep 
      if [ $? = 0 ]; then
        echo "Running."
      fi
    else
      echo "Not running."
    fi
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
exit 0
